 /**
* @class StackedBar3DChart
* @author InfoSoft Global (P) Ltd. www.InfoSoftGlobal.com
* @version 3.0
*
* Copyright (C) InfoSoft Global Pvt. Ltd. 2005-2006
*
* StackedBar3DChart chart extends the SingleYAxis3DChart class to render a
* Stacked 3D Bar Chart.
*/
//Import Chart class
import com.fusioncharts.core.Chart;
//Parent SingleYAxis3DHorizontalChart Class
import com.fusioncharts.core.SingleYAxis3DHorizontalChart;
//Error class
import com.fusioncharts.helper.FCError;
//Import Logger Class
import com.fusioncharts.helper.Logger;
//Style Object
import com.fusioncharts.core.StyleObject;
//Delegate
import mx.utils.Delegate;
//Legend Class
import com.fusioncharts.helper.Legend;
//Bars
import com.fusioncharts.core.chartobjects.Bar3D;
//Extensions
import com.fusioncharts.extensions.ColorExt;
import com.fusioncharts.extensions.StringExt;
import com.fusioncharts.extensions.MathExt;
import com.fusioncharts.extensions.DrawingExt;
class com.fusioncharts.core.charts.StackedBar3DChart extends SingleYAxis3DHorizontalChart
{
	//Version number (if different from super Chart class)
	//private var _version:String = "3.0.0";
	//Instance variables
	//List of chart objects
	private var _arrObjects : Array;
	private var xmlData : XML;
	//Array to store x-axis categories (labels)
	private var categories : Array;
	//Array to store datasets
	private var dataset : Array;
	//Number of data sets
	private var numDS : Number;
	//Number of data items
	private var num : Number;
	//Reference to legend component of chart
	private var lgnd : Legend;
	//Reference to legend movie clip
	private var lgndMC : MovieClip;
	//Flag to indicate whether positive number is present
	private var positivePresent : Boolean;
	//Flag to indicate whether negative number is present
	private var negativePresent : Boolean;
	//Array to store Sums
	private var sums : Array;
	private var sumStored : Boolean;
	/**
	* Constructor function. We invoke the super class'
	* constructor and then set the objects for this chart.
	*/
	function StackedBar3DChart (targetMC : MovieClip, depth : Number, width : Number, height : Number, x : Number, y : Number, debugMode : Boolean, lang : String, scaleMode:String, registerWithJS:Boolean, DOMId:String)
	{
		//Invoke the super class constructor
		super (targetMC, depth, width, height, x, y, debugMode, lang, scaleMode, registerWithJS, DOMId);
		//Log additional information to debugger
		//We log version from this class, so that if this class version
		//is different, we can log it
		this.log ("Version", _version, Logger.LEVEL.INFO);
		this.log ("Chart Type", "Stacked 3D Bar Chart", Logger.LEVEL.INFO);
		//List Chart Objects and set them
		_arrObjects = new Array ("BACKGROUND", "CANVAS", "CAPTION", "SUBCAPTION", "YAXISNAME", "XAXISNAME", "DIVLINES", "YAXISVALUES", "DATALABELS", "DATAVALUES", "TRENDLINES", "TRENDVALUES", "DATAPLOT", "TOOLTIP", "VLINES", "LEGEND", "VLINELABELS");
		super.setChartObjects (_arrObjects);
		//Initialize the containers for chart
		this.categories = new Array ();
		this.dataset = new Array ();
		//Initialize the number of data elements present
		this.numDS = 0;
		this.num = 0;
		this.negativePresent = false;
		this.positivePresent = false;
		//Array to store sum of data sets
		this.sums = new Array ();
		this.sumStored = false;
	}
	/**
	* render method is the single call method that does the rendering of chart:
	* - Parsing XML
	* - Calculating values and co-ordinates
	* - Visual layout and rendering
	* - Event handling
	*/
	public function render () : Void
	{
		//Parse the XML Data document
		this.parseXML ();
		//Now, if the number of data elements is 0, we show pertinent
		//error.
		if (this.numDS * this.num == 0)
		{
			tfAppMsg = this.renderAppMessage (_global.getAppMessage ("NODATA", this.lang));
			//Add a message to log.
			this.log ("No Data to Display", "No data was found in the XML data document provided. Possible cases can be: <LI>There isn't any data generated by your system. If your system generates data based on parameters passed to it using dataURL, please make sure dataURL is URL Encoded.</LI><LI>You might be using a Single Series Chart .swf file instead of Multi-series .swf file and providing multi-series data or vice-versa.</LI>", Logger.LEVEL.ERROR);
			//Expose rendered method
			this.exposeChartRendered();
			//Also raise the no data event
			this.raiseNoDataExternalEvent();
		} else
		{
			//Detect number scales
			this.detectNumberScales ();
			//Calculate the axis limits
			this.calculateAxisLimits ();
			//Calculate exact number of div lines
			this.calcDivs ();
			//Set Style defaults
			this.setStyleDefaults ();
			//Validate trend lines
			this.validateTrendLines ();
			//Allot the depths for various charts objects now
			this.allotDepths ();
			//Calculate Points
			this.calculatePoints ();
			//Calculate vLine Positions
			this.calcVLinesPos ();
			//Calculate trend line positions
			this.calcTrendLinePos ();
			//Feed macro values
			this.feedMacros ();
			//Remove application message
			this.removeAppMessage (this.tfAppMsg);
			//Set tool tip parameter
			this.setToolTipParam ();
			//-----Start Visual Rendering Now------//
			//Draw background
			this.drawBackground ();
			//Set click handler
			this.drawClickURLHandler ()
			//Load background SWF
			this.loadBgSWF ();
			//Update timer
			this.timeElapsed = (this.params.animation) ? this.styleM.getMaxAnimationTime (this.objects.BACKGROUND) : 0;
			//Draw canvas
			this.config.intervals.canvas = setInterval (Delegate.create (this, drawCanvas) , this.timeElapsed);
			//Draw headers
			this.config.intervals.headers = setInterval (Delegate.create (this, drawHeaders) , this.timeElapsed);
			//Update timer
			this.timeElapsed += (this.params.animation) ? this.styleM.getMaxAnimationTime (this.objects.CANVAS, this.objects.CAPTION, this.objects.SUBCAPTION, this.objects.YAXISNAME, this.objects.XAXISNAME) : 0;
			//Draw div lines
			this.config.intervals.divLines = setInterval (Delegate.create (this, drawDivLines) , this.timeElapsed);
			//Update timer
			this.timeElapsed += (this.params.animation) ? this.styleM.getMaxAnimationTime (this.objects.DIVLINES, this.objects.YAXISVALUES) : 0;
			//Draw labels
			this.config.intervals.labels = setInterval (Delegate.create (this, drawLabels) , this.timeElapsed);			
			//Draw bars
			this.config.intervals.plot = setInterval (Delegate.create (this, drawBars) , this.timeElapsed);
			//Legend
			this.config.intervals.legend = setInterval (Delegate.create (this, drawLegend) , this.timeElapsed);
			//Update timer
			this.timeElapsed += (this.params.animation) ? this.styleM.getMaxAnimationTime (this.objects.DATALABELS, this.objects.DATAPLOT, this.objects.LEGEND) : 0;
			//Data Values
			this.config.intervals.dataValues = setInterval (Delegate.create (this, drawValues) , this.timeElapsed);
			//Data Sum
			this.config.intervals.dataSum = setInterval (Delegate.create (this, drawSum) , this.timeElapsed);
			//Draw trend lines
			this.config.intervals.trend = setInterval (Delegate.create (this, drawTrendLines) , this.timeElapsed);
			//Draw vertical div lines
			this.config.intervals.vLine = setInterval (Delegate.create (this, drawVLines) , this.timeElapsed);
			//Update timer
			this.timeElapsed += (this.params.animation) ? this.styleM.getMaxAnimationTime (this.objects.TRENDLINES, this.objects.TRENDVALUES, this.objects.VLINES, this.objects.DATAVALUES) : 0;
			//Dispatch event that the chart has loaded.
			this.config.intervals.renderedEvent = setInterval(Delegate.create(this, exposeChartRendered) , this.timeElapsed);
			//Render context menu
			//We do not put context menu interval as we need the menu to appear
			//right from start of the play.
			this.setContextMenu ();
		}
	}
	/**
	* returnDataAsObject method creates an object out of the parameters
	* passed to this method. The idea is that we store each data point
	* as an object with multiple (flexible) properties. So, we do not
	* use a predefined class structure. Instead we use a generic object.
	*	@param	value		Value for the bar.
	*	@param	color		Hex Color code (or comma separated list).
	* 	@param	displayValue	Value that will be displayed on the chart
	*	@param	alpha		List of alphas separated by comma
	*	@param	ratio		List of color ratios separated by comma
	*	@param	toolText	Tool tip text (if specified).
	*	@param	link		Link (if any) for the bar.
	*	@param	showValue	Flag to show/hide value for this bar.
	*	@param	isDashed	Flag whether the bar would have dashed border.
	*	@return			An object encapsulating all these properies.
	*/
	private function returnDataAsObject (value : Number, color : String, displayValue:String, alpha : Number, toolText : String, link : String, showValue : Number) : Object
	{
		//Create a container
		var dataObj : Object = new Object ();
		//Store the values
		dataObj.value = value;
		//Explicitly specified display value
		dataObj.exDispVal = displayValue;
		//Extract and save colors, ratio, alpha as array so that we do not have to parse later.
		dataObj.color = color;
		dataObj.alpha = alpha;
		dataObj.toolText = toolText;
		dataObj.link = link;
		dataObj.showValue = (showValue == 1) ? true : false;
		//If the given number is not a valid number or it's missing
		//set appropriate flags for this data point
		dataObj.isDefined = ((dataObj.alpha == 0) || isNaN (value)) ? false : true;
		//Other parameters
		//X & Y Position of data point
		dataObj.x = 0;
		dataObj.y = 0;
		//Width and height
		dataObj.w = 0;
		dataObj.h = 0;
		//X & Y Position of value tb
		dataObj.valTBX = 0;
		dataObj.valTBY = 0;
		//Return the container
		return dataObj;
	}
	/**
	* returnDataAsCat method returns data of a <category> element as
	* an object
	*	@param	label		Label of the category.
	*	@param	showLabel	Whether to show the label of this category.
	*	@param	toolText	Tool-text for the category
	*	@return			A container object with the given properties
	*/
	private function returnDataAsCat (label : String, showLabel : Number, toolText : String) : Object
	{
		//Create container object
		var catObj : Object = new Object ();
		catObj.label = label;
		catObj.showLabel = ((showLabel == 1) && (label != undefined) && (label != null) && (label != "")) ? true : false;
		catObj.toolText = toolText;
		//X and Y Position
		catObj.x = 0;
		catObj.y = 0;
		//Return container
		return catObj;
	}
	/**
	* parseXML method parses the XML data, sets defaults and validates
	* the attributes before storing them to data storage objects.
	*/
	private function parseXML () : Void
	{
		//Get the element nodes
		var arrDocElement : Array = this.xmlData.childNodes;
		//Loop variable
		var i : Number;
		var j : Number;
		var k : Number;
		//Look for <graph> element
		for (i = 0; i < arrDocElement.length; i ++)
		{
			//If it's a <graph> element, proceed.
			//Do case in-sensitive mathcing by changing to upper case
			if (arrDocElement [i].nodeName.toUpperCase () == "GRAPH" || arrDocElement [i].nodeName.toUpperCase () == "CHART")
			{
				//Extract attributes of <graph> element
				this.parseAttributes (arrDocElement [i]);
				//Extract common attributes/over-ride chart specific ones
				this.parseCommonAttributes (arrDocElement [i],false);
				//Now, get the child nodes - first level nodes
				//Level 1 nodes can be - CATEGORIES, DATASET, TRENDLINES, STYLES etc.
				var arrLevel1Nodes : Array = arrDocElement [i].childNodes;
				var setNode : XMLNode;
				//Iterate through all level 1 nodes.
				for (j = 0; j < arrLevel1Nodes.length; j ++)
				{
					if (arrLevel1Nodes [j].nodeName.toUpperCase () == "CATEGORIES")
					{
						//Categories Node.
						var categoriesNode : XMLNode = arrLevel1Nodes [j];
						//Convert attributes to array
						var categoriesAtt : Array = this.getAttributesArray (categoriesNode);
						//Extract attributes of this node.
						this.params.catFont = getFV (categoriesAtt ["font"] , this.params.outCnvBaseFont);
						this.params.catFontSize = getFN (categoriesAtt ["fontsize"] , this.params.outCnvBaseFontSize);
						this.params.catFontColor = formatColor (getFV (categoriesAtt ["fontcolor"] , this.params.outCnvBaseFontColor));
						//Get reference to child node.
						var arrLevel2Nodes : Array = arrLevel1Nodes [j].childNodes;
						//Iterate through all child-nodes of CATEGORIES element
						//and search for CATEGORY or VLINE node
						for (k = 0; k < arrLevel2Nodes.length; k ++)
						{
							if (arrLevel2Nodes [k].nodeName.toUpperCase () == "CATEGORY")
							{
								//Category Node.
								//Update counter
								this.num ++;
								//Extract attributes
								var categoryNode : XMLNode = arrLevel2Nodes [k];
								var categoryAtt : Array = this.getAttributesArray (categoryNode);
								//Category label.
								var catLabel : String = getFV (categoryAtt ["label"] , categoryAtt ["name"] , "");
								var catShowLabel : Number = getFN (categoryAtt ["showlabel"] , categoryAtt ["showname"] , this.params.showLabels);
								var catToolText : String = getFV (categoryAtt ["tooltext"] , categoryAtt ["hovertext"] , catLabel);
								//Store it in data container.
								this.categories [this.num] = this.returnDataAsCat (catLabel, catShowLabel, catToolText);
							} 
							else if (arrLevel2Nodes [k].nodeName.toUpperCase () == "VLINE")
							{
								//Vertical axis division Node - extract child nodes
								var vLineNode : XMLNode = arrLevel2Nodes [k];
								//Parse and store
								this.parseVLineNode (vLineNode, this.num);
							}
						}
					} else if (arrLevel1Nodes [j].nodeName.toUpperCase () == "DATASET")
					{
						//Increment
						this.numDS ++;
						//Dataset node.
						var dataSetNode : XMLNode = arrLevel1Nodes [j];
						//Get attributes array
						var dsAtts : Array = this.getAttributesArray (dataSetNode);
						//Create storage object in dataset array
						this.dataset [this.numDS] = new Object ();
						//Store attributes
						this.dataset [this.numDS].seriesName = getFV (dsAtts ["seriesname"] , "");
						this.dataset [this.numDS].color = getFV (dsAtts ["color"] , this.defColors.getColor ());
						this.dataset [this.numDS].alpha = getFN (dsAtts ["alpha"] , this.params.plotFillAlpha);
						this.dataset [this.numDS].showValues = toBoolean (getFN (dsAtts ["showvalues"] , this.params.showValues));
						this.dataset [this.numDS].dashed = toBoolean (getFN (dsAtts ["dashed"] , this.params.plotBorderDashed));
						this.dataset [this.numDS].includeInLegend = toBoolean (getFN (dsAtts ["includeinlegend"] , 1));
						//Create data array under it.
						this.dataset [this.numDS].data = new Array ();
						//Get reference to child node.
						var arrLevel2Nodes : Array = arrLevel1Nodes [j].childNodes;
						//Iterate through all child-nodes of DATASET element
						//and search for SET node
						//Counter
						var setCount : Number = 0;
						for (k = 0; k < arrLevel2Nodes.length; k ++)
						{
							if (arrLevel2Nodes [k].nodeName.toUpperCase () == "SET")
							{
								//Set Node. So extract the data.
								//Update counter
								setCount ++;
								//Get reference to node.
								setNode = arrLevel2Nodes [k];
								//Get attributes
								var atts : Array;
								atts = this.getAttributesArray (setNode);
								//Now, get value.
								var setValue : Number = this.getSetValue (atts ["value"]);
								//Get explicitly specified display value
								var setExDispVal : String = getFV( atts["displayvalue"], "");
								//We do NOT unescape the link, as this will be done
								//in invokeLink method for the links that user clicks.
								var setLink : String = getFV (atts ["link"] , "");
								var setToolText : String = getFV (atts ["tooltext"] , atts ["hovertext"]);
								var setColor : String = getFV (atts ["color"] , this.dataset [this.numDS].color);
								var setAlpha : Number = getFN (atts ["alpha"] , this.dataset [this.numDS].alpha);
								var setShowValue : Number = getFN (atts ["showvalue"] , this.dataset [this.numDS].showValues);
								//Store all these attributes as object.
								this.dataset [this.numDS].data [setCount] = this.returnDataAsObject (setValue, setColor, setExDispVal,  setAlpha, setToolText, setLink, setShowValue);
								//Update numNeg, numPos based on set value
								if (setValue < 0)
								{
									//Update negative count
									numNeg ++;
								} else
								{
									//Update positive count
									numPos ++;
								}
								//Update negative flag
								this.negativePresent = (setValue < 0) ?true : negativePresent;
								this.positivePresent = (setValue >= 0) ?true : positivePresent;
							}
						}
					} else if (arrLevel1Nodes [j].nodeName.toUpperCase () == "STYLES")
					{
						//Styles Node - extract child nodes
						var arrStyleNodes : Array = arrLevel1Nodes [j].childNodes;
						//Parse the style nodes to extract style information
						super.parseStyleXML (arrStyleNodes);
					} else if (arrLevel1Nodes [j].nodeName.toUpperCase () == "TRENDLINES")
					{
						//Trend lines node
						var arrTrendNodes : Array = arrLevel1Nodes [j].childNodes;
						//Parse the trend line nodes
						super.parseTrendLineXML (arrTrendNodes);
					}
				}
			}
		}
		//Delete all temporary objects used for parsing XML Data document
		delete setNode;
		delete arrDocElement;
		delete arrLevel1Nodes;
		delete arrLevel2Nodes;
	}
	/**
	* parseAttributes method parses the attributes and stores them in
	* chart storage objects.
	* Starting ActionScript 2, the parsing of XML attributes have also
	* become case-sensitive. However, prior versions of FusionCharts
	* supported case-insensitive attributes. So we need to parse all
	* attributes as case-insensitive to maintain backward compatibility.
	* To do so, we first extract all attributes from XML, convert it into
	* lower case and then store it in an array. Later, we extract value from
	* this array.
	* @param	graphElement	XML Node containing the <graph> element
	*							and it's attributes
	*/
	private function parseAttributes (graphElement : XMLNode) : Void
	{
		//Array to store the attributes
		var atts : Array = this.getAttributesArray (graphElement);
		//NOW IT'S VERY NECCESARY THAT WHEN WE REFERENCE THIS ARRAY
		//TO GET AN ATTRIBUTE VALUE, WE SHOULD PROVIDE THE ATTRIBUTE
		//NAME IN LOWER CASE. ELSE, UNDEFINED VALUE WOULD SHOW UP.
		//Extract attributes pertinent to this chart
		//Which palette to use?
		this.params.palette = getFN (atts ["palette"] , 1);
		//Palette colors to use
		this.params.paletteColors = getFV(atts["palettecolors"],"");
		//Set palette colors before parsing the <set> nodes.
		this.setPaletteColors();
		// ---------- PADDING AND SPACING RELATED ATTRIBUTES ----------- //
		//captionPadding = Space between caption/subcaption and canvas start Y
		this.params.captionPadding = getFN (atts ["captionpadding"] , 10);
		//canvasPadding - Padding on the canvas on top and bottom side of bar
		this.params.canvasPadding = getFN (atts ["canvaspadding"] , 10);
		//Padding for x-axis name - to the left
		this.params.xAxisNamePadding = getFN (atts ["xaxisnamepadding"] , 5);
		//Padding for y-axis name - to right
		this.params.yAxisNamePadding = getFN (atts ["yaxisnamepadding"] , 5);
		//Y-Axis Values padding - Vertical space between the axis edge and
		//y-axis values or trend line values.
		this.params.yAxisValuesPadding = getFN (atts ["yaxisvaluespadding"] , 2);
		//Label padding - Vertical space between the labels and canvas start position
		this.params.labelPadding = getFN (atts ["labelpadding"] , atts ["labelspadding"] , 3);
		//Value padding - Horizontal space between the end of bars and start of value textboxes
		this.params.valuePadding = getFN (atts ["valuepadding"] , 2);
		//Percentage space on the plot area
		this.params.plotSpacePercent = getFN (atts ["plotspacepercent"] , 20);
		///Cannot be less than 0 and more than 80
		if ((this.params.plotSpacePercent < 0) || (this.params.plotSpacePercent > 80))
		{
			//Reset to 20
			this.params.plotSpacePercent = 20;
		}
		//Padding of legend from right/bottom side of canvas
		this.params.legendPadding = getFN (atts ["legendpadding"] , 6);
		//Chart Margins - Empty space at the 4 sides
		this.params.chartLeftMargin = getFN (atts ["chartleftmargin"] , 15);
		this.params.chartRightMargin = getFN (atts ["chartrightmargin"] , 30);
		this.params.chartTopMargin = getFN (atts ["charttopmargin"] , 15);
		this.params.chartBottomMargin = getFN (atts ["chartbottommargin"] , 15);
		// -------------------------- HEADERS ------------------------- //
		//Chart Caption and sub Caption
		this.params.caption = getFV (atts ["caption"] , "");
		this.params.subCaption = getFV (atts ["subcaption"] , "");
		//X and Y Axis Name
		this.params.xAxisName = getFV (atts ["xaxisname"] , "");
		this.params.yAxisName = getFV (atts ["yaxisname"] , "");
		// --------------------- CONFIGURATION ------------------------- //
		//The upper and lower limits of y and x axis
		//In a stacked bar chart, users cannot set yAxisMinValue as it always
		//emanates from 0.
		//this.params.yAxisMinValue = atts["yaxisminvalue"];
		this.params.yAxisMaxValue = atts ["yaxismaxvalue"];
		//Whether to set animation for entire chart.
		this.params.animation = toBoolean (getFN (atts ["animation"] , 1));
		//Whether to set the default chart animation
		this.params.defaultAnimation = toBoolean (getFN (atts ["defaultanimation"] , 1));
		//Whether to overlap bars
		this.params.overlapBars = atts ["overlapbars"];
		//Maximum allowed bar height
		this.params.maxBarHeight = getFN (atts ["maxbarheight"] , 100);
		//Configuration to set whether to show the labels
		this.params.showLabels = toBoolean (getFN (atts ["showlabels"] , atts ["shownames"] , 1));
		//Step value for labels - i.e., show all labels or skip every x label
		this.params.labelStep = int (getFN (atts ["labelstep"] , 1));
		//Cannot be less than 1
		this.params.labelStep = (this.params.labelStep < 1) ? 1 : this.params.labelStep;
		//Configuration whether to show data values
		this.params.showValues = toBoolean (getFN (atts ["showvalues"] , 1));
		//Configuration whether to show data sum
		this.params.showSum = toBoolean (getFN (atts ["showsum"] , 0));
		//Option to show/hide y-axis values
		this.params.showYAxisValues = getFN (atts ["showyaxisvalues"] , atts ["showyaxisvalue"] , 1);
		this.params.showLimits = toBoolean (getFN (atts ["showlimits"] , this.params.showYAxisValues));
		this.params.showDivLineValues = toBoolean (getFN (atts ["showdivlinevalue"] , atts ["showdivlinevalues"] , this.params.showYAxisValues));
		//Y-axis value step- i.e., show all y-axis or skip every x(th) value
		this.params.yAxisValuesStep = int (getFN (atts ["yaxisvaluesstep"] , atts ["yaxisvaluestep"] , 1));
		//Cannot be less than 1
		this.params.yAxisValuesStep = (this.params.yAxisValuesStep < 1) ? 1 : this.params.yAxisValuesStep;
		//Whether to automatically adjust div lines
		this.params.adjustDiv = toBoolean (getFN (atts ["adjustdiv"] , 1));
		//Whether to rotate x-axis name
		this.params.rotateXAxisName = toBoolean (getFN (atts ["rotatexaxisname"] , 1));
		//Max width to be alloted to x-axis name - No defaults, as it's calculated later.
		this.params.xAxisNameWidth = atts ["xaxisnamewidth"];
		//Bar Depth
		this.params.barDepth = getFN (atts ["bardepth"] , - 1)
		//Click URL
		this.params.clickURL = getFV (atts ["clickurl"] , "");
		// ------------------------- COSMETICS -----------------------------//
		//Whether to use 3D Lighting
		this.params.use3DLighting = toBoolean (getFN (atts ["use3dlighting"] , 1));
		//Show bar shadows
		this.params.showShadow = toBoolean (getFN (atts ["showshadow"] , this.params.use3DLighting));
		//Background properties - Gradient
		this.params.bgColor = getFV (atts ["bgcolor"] , this.defColors.getBgColor3D (this.params.palette));
		this.params.bgAlpha = getFV (atts ["bgalpha"] , this.defColors.getBgAlpha3D (this.params.palette));
		this.params.bgRatio = getFV (atts ["bgratio"] , this.defColors.getBgRatio3D (this.params.palette));
		this.params.bgAngle = getFV (atts ["bgangle"] , this.defColors.getBgAngle3D (this.params.palette));
		//Border Properties of chart
		this.params.showBorder = toBoolean (getFN (atts ["showborder"] , 0));
		this.params.borderColor = formatColor (getFV (atts ["bordercolor"] , "666666"));
		this.params.borderThickness = getFN (atts ["borderthickness"] , 1);
		this.params.borderAlpha = getFN (atts ["borderalpha"] , 100);
		//Canvas background properties
		this.params.canvasBgColor = formatColor (getFV (atts ["canvasbgcolor"] , this.defColors.getCanvasBgColor3D (this.params.palette)));
		this.params.canvasBgAlpha = getFN (atts ["canvasbgalpha"] , 100);
		this.params.canvasBaseColor = formatColor (getFV (atts ["canvasbasecolor"] , this.defColors.getCanvasBaseColor3D (this.params.palette)));
		//Option to show/hide canvas base and bg
		this.params.showCanvasBg = toBoolean (getFN (atts ["showcanvasbg"] , 1));
		this.params.showCanvasBase = toBoolean (getFN (atts ["showcanvasbase"] , 1));
		//Depth of background and base
		this.params.canvasBaseDepth = getFN (atts ["canvasbasedepth"] , 10);
		this.params.canvasBgDepth = getFN (atts ["canvasbgdepth"] , 3);
		//Plot cosmetic properties
		this.params.showPlotBorder = toBoolean (getFN (atts ["showplotborder"] , 0));
		this.params.plotBorderColor = formatColor (getFV (atts ["plotbordercolor"] , "FFFFFF"));
		this.params.plotBorderAlpha = getFN (atts ["plotborderalpha"] , (this.params.showPlotBorder == true) ?95 : 0);
		//Fill properties
		this.params.plotFillAlpha = getFN (atts ["plotfillalpha"] , 100);
		//Legend properties
		this.params.showLegend = toBoolean (getFN (atts ["showlegend"] , 1));
		//Alignment position
		this.params.legendPosition = getFV (atts ["legendposition"] , "BOTTOM");
		//Legend position can be either RIGHT or BOTTOM -Check for it
		this.params.legendPosition = (this.params.legendPosition.toUpperCase () == "RIGHT") ?"RIGHT" : "BOTTOM";
		this.params.legendCaption = getFV(atts ["legendcaption"] , "");
		this.params.legendMarkerCircle = toBoolean(getFN(atts ["legendmarkercircle"] , 0));
		this.params.legendBorderColor = formatColor (getFV (atts ["legendbordercolor"] , this.defColors.getLegendBorderColor3D (this.params.palette)));
		this.params.legendBorderThickness = getFN (atts ["legendborderthickness"] , 1);
		this.params.legendBorderAlpha = getFN (atts ["legendborderalpha"] , 100);
		this.params.legendBgColor = getFV (atts ["legendbgcolor"] , this.defColors.getLegendBgColor3D (this.params.palette));
		this.params.legendBgAlpha = getFN (atts ["legendbgalpha"] , 100);
		this.params.legendShadow = toBoolean (getFN (atts ["legendshadow"] , 1));
		this.params.legendAllowDrag = toBoolean (getFN (atts ["legendallowdrag"] , 0));
		this.params.legendScrollBgColor = formatColor (getFV (atts ["legendscrollbgcolor"] , "CCCCCC"));
		this.params.legendScrollBarColor = formatColor (getFV (atts ["legendscrollbarcolor"] , this.params.legendBorderColor));
		this.params.legendScrollBtnColor = formatColor (getFV (atts ["legendscrollbtncolor"] , this.params.legendBorderColor));
		this.params.reverseLegend = toBoolean (getFN (atts ["reverselegend"] , 0));
		//Horizontal grid division Lines - Number, color, thickness & alpha
		//Necessarily need a default value for numDivLines.
		this.params.numDivLines = getFN (atts ["numdivlines"] , 4);
		this.params.divLineColor = formatColor (getFV (atts ["divlinecolor"] , this.defColors.getDivLineColor3D (this.params.palette)));
		this.params.divLineThickness = getFN (atts ["divlinethickness"] , 1);
		this.params.divLineAlpha = getFN (atts ["divlinealpha"] , 100);
		this.params.divLineIsDashed = toBoolean (getFN (atts ["divlineisdashed"] , 0));
		this.params.divLineDashLen = getFN (atts ["divlinedashlen"] , 4);
		this.params.divLineDashGap = getFN (atts ["divlinedashgap"] , 2);
		//Zero Plane properties
		this.params.showZeroPlane = true;
		this.params.zeroPlaneColor = formatColor (getFV (atts ["zeroplanecolor"] , this.params.divLineColor));
		this.params.zeroPlaneAlpha = getFN (atts ["zeroplanealpha"] , 75);
		this.params.zeroPlaneShowBorder = toBoolean (getFN (atts ["zeroplaneshowborder"] , 1));
		this.params.zeroPlaneBorderColor = formatColor (getFV (atts ["zeroplanebordercolor"] , this.params.zeroPlaneColor));
		// ------------------------- NUMBER FORMATTING ---------------------------- //
		//Option whether the format the number (using Commas)
		this.params.formatNumber = toBoolean (getFN (atts ["formatnumber"] , 1));
		//Option to format number scale
		this.params.formatNumberScale = toBoolean (getFN (atts ["formatnumberscale"] , 1));
		//Number Scales
		this.params.defaultNumberScale = getFV (atts ["defaultnumberscale"] , "");
		this.params.numberScaleUnit = getFV (atts ["numberscaleunit"] , "K,M");
		this.params.numberScaleValue = getFV (atts ["numberscalevalue"] , "1000,1000");
		//Number prefix and suffix
		this.params.numberPrefix = getFV (atts ["numberprefix"] , "");
		this.params.numberSuffix = getFV (atts ["numbersuffix"] , "");
		//Decimal Separator Character
		this.params.decimalSeparator = getFV (atts ["decimalseparator"] , ".");
		//Thousand Separator Character
		this.params.thousandSeparator = getFV (atts ["thousandseparator"] , ",");
		//Input decimal separator and thousand separator. In some european countries,
		//commas are used as decimal separators and dots as thousand separators. In XML,
		//if the user specifies such values, it will give a error while converting to
		//number. So, we accept the input decimal and thousand separator from user, so that
		//we can covert it accordingly into the required format.
		this.params.inDecimalSeparator = getFV (atts ["indecimalseparator"] , "");
		this.params.inThousandSeparator = getFV (atts ["inthousandseparator"] , "");
		//Decimal Precision (number of decimal places to be rounded to)
		this.params.decimals = getFV (atts ["decimals"] , atts ["decimalprecision"]);
		//Force Decimal Padding
		this.params.forceDecimals = toBoolean (getFN (atts ["forcedecimals"] , 0));
		//y-Axis values decimals
		this.params.yAxisValueDecimals = getFV (atts ["yaxisvaluedecimals"] , atts ["yaxisvaluesdecimals"] , atts ["divlinedecimalprecision"] , atts ["limitsdecimalprecision"]);
	}
	/**
	* getSumOfValues method returns the sum of values of a particular data
	* index in all the data sets. It is used to get the positive and negative
	* sum for the given index.
	*	@param	index	Index for which we've to calculate sum
	*	@return		An object containing PSum and NSum as positive
	*					and negative sum respectively.
	*/
	private function getSumOfValues (index : Number) : Object
	{
		//Loop variables
		var i : Number;
		//Variable to store positive and negative sum
		var pSum : Number, nSum : Number;
		//Return Object
		var rtnObj : Object = new Object ();
		//Iterate through all the datasets for this index
		for (i = 1; i <= this.numDS; i ++)
		{
			//Check only if the data is defined
			if (this.dataset [i].data [index].isDefined)
			{
				if (this.dataset [i].data [index].value >= 0)
				{
					pSum = (pSum == undefined) ? (this.dataset [i].data [index].value) : (pSum + this.dataset [i].data [index].value);
				} else
				{
					nSum = (nSum == undefined) ? (this.dataset [i].data [index].value) : (nSum + this.dataset [i].data [index].value);
				}
			}
		}
		if (this.sumStored == false)
		{
			//Store the sum of this index in array
			this.sums [index] = new Object ();
			this.sums [index].sum = ((pSum == undefined) ?0 : pSum) + ((nSum == undefined) ?0 : nSum);
			this.sums [index].pSum = pSum;
			this.sums [index].nSum = nSum;
			//Update flag
			if (index == this.num)
			{
				this.sumStored = true;
			}
		}
		//Store values in return object and return
		rtnObj.pSum = pSum;
		rtnObj.nSum = nSum;
		return rtnObj;
	}
	/**
	* getMaxDataValue method gets the maximum y-axis data sum present
	* in the data.
	*	@return	The maximum value present in the data provided.
	*/
	private function getMaxDataValue () : Number
	{
		var maxValue : Number;
		var firstSumFound : Boolean = false;
		var i : Number;
		var pSum : Number, sNum : Number;
		var sumObj : Object;
		var vitalSum : Number;
		for (i = 1; i <= this.num; i ++)
		{
			sumObj = this.getSumOfValues (i);
			vitalSum = (this.positivePresent == false) ? (sumObj.nSum) : (sumObj.pSum);
			//By default assume the first non-null sum to be maximum
			if (firstSumFound == false)
			{
				if (vitalSum != undefined)
				{
					//Set the flag that "We've found first non-null sum".
					firstSumFound = true;
					//Also assume this value to be maximum.
					maxValue = vitalSum;
				}
			} else
			{
				//If the first sum has been found and the current sum is defined, compare
				if (vitalSum != undefined)
				{
					//Store the greater number
					maxValue = (vitalSum > maxValue) ? vitalSum : maxValue;
				}
			}
		}
		return maxValue;
	}
	/**
	* getMinDataValue method gets the minimum y-axis data sum present
	* in the data
	*	@reurns		The minimum value present in data
	*/
	private function getMinDataValue () : Number
	{
		var minValue : Number;
		var firstSumFound : Boolean = false;
		var i : Number;
		var pSum : Number, sNum : Number;
		var sumObj : Object;
		var vitalSum : Number;
		for (i = 1; i <= this.num; i ++)
		{
			sumObj = this.getSumOfValues (i);
			vitalSum = (this.negativePresent == true) ? (sumObj.nSum) : (sumObj.pSum);
			//By default assume the first non-null sum to be minimum
			if (firstSumFound == false)
			{
				if (vitalSum != undefined)
				{
					//Set the flag that "We've found first non-null sum".
					firstSumFound = true;
					//Also assume this value to be minimum.
					minValue = vitalSum;
				}
			} else
			{
				//If the first sum has been found and the current sum is defined, compare
				if (vitalSum != undefined)
				{
					//Store the lesser number
					minValue = (vitalSum < minValue) ? vitalSum : minValue;
				}
			}
		}
		return minValue;
	}
	/**
	* calculateAxisLimits method sets the axis limits for the chart.
	* It gets the minimum and maximum value specified in data and
	* based on that it calls super.getAxisLimits();
	*/
	private function calculateAxisLimits () : Void
	{
		this.getAxisLimits (this.getMaxDataValue () , this.getMinDataValue () , true, true);
	}
	/**
	* setStyleDefaults method sets the default values for styles or
	* extracts information from the attributes and stores them into
	* style objects.
	*/
	private function setStyleDefaults () : Void
	{
		//Default font object for Caption
		//-----------------------------------------------------------------//
		var captionFont = new StyleObject ();
		captionFont.name = "_SdCaptionFont";
		captionFont.align = "center";
		captionFont.valign = "top";
		captionFont.bold = "1";
		captionFont.font = this.params.outCnvBaseFont;
		captionFont.size = this.params.outCnvBaseFontSize;
		captionFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.CAPTION, captionFont, this.styleM.TYPE.FONT, null);
		delete captionFont;
		//-----------------------------------------------------------------//
		//Default font object for SubCaption
		//-----------------------------------------------------------------//
		var subCaptionFont = new StyleObject ();
		subCaptionFont.name = "_SdSubCaptionFont";
		subCaptionFont.align = "center";
		subCaptionFont.valign = "top";
		subCaptionFont.bold = "1";
		subCaptionFont.font = this.params.outCnvBaseFont;
		subCaptionFont.size = this.params.outCnvBaseFontSize;
		subCaptionFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.SUBCAPTION, subCaptionFont, this.styleM.TYPE.FONT, null);
		delete subCaptionFont;
		//-----------------------------------------------------------------//
		//Default font object for YAxisName
		//-----------------------------------------------------------------//
		var yAxisNameFont = new StyleObject ();
		yAxisNameFont.name = "_SdYAxisNameFont";
		yAxisNameFont.align = "center";
		yAxisNameFont.valign = "middle";
		yAxisNameFont.bold = "1";
		yAxisNameFont.font = this.params.outCnvBaseFont;
		yAxisNameFont.size = this.params.outCnvBaseFontSize;
		yAxisNameFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.YAXISNAME, yAxisNameFont, this.styleM.TYPE.FONT, null);
		delete yAxisNameFont;
		//-----------------------------------------------------------------//
		//Default font object for XAxisName
		//-----------------------------------------------------------------//
		var xAxisNameFont = new StyleObject ();
		xAxisNameFont.name = "_SdXAxisNameFont";
		xAxisNameFont.align = "center";
		xAxisNameFont.valign = "middle";
		xAxisNameFont.bold = "1";
		xAxisNameFont.font = this.params.outCnvBaseFont;
		xAxisNameFont.size = this.params.outCnvBaseFontSize;
		xAxisNameFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.XAXISNAME, xAxisNameFont, this.styleM.TYPE.FONT, null);
		delete xAxisNameFont;
		//-----------------------------------------------------------------//
		//Default font object for trend lines
		//-----------------------------------------------------------------//
		var trendFont = new StyleObject ();
		trendFont.name = "_SdTrendFont";
		trendFont.font = this.params.outCnvBaseFont;
		trendFont.size = this.params.outCnvBaseFontSize;
		trendFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.TRENDVALUES, trendFont, this.styleM.TYPE.FONT, null);
		delete trendFont;
		//-----------------------------------------------------------------//
		//Default font object for yAxisValues
		//-----------------------------------------------------------------//
		var yAxisValuesFont = new StyleObject ();
		yAxisValuesFont.name = "_SdYAxisValuesFont";
		yAxisValuesFont.align = "right";
		yAxisValuesFont.valign = "middle";
		yAxisValuesFont.font = this.params.outCnvBaseFont;
		yAxisValuesFont.size = this.params.outCnvBaseFontSize;
		yAxisValuesFont.color = this.params.outCnvBaseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.YAXISVALUES, yAxisValuesFont, this.styleM.TYPE.FONT, null);
		delete yAxisValuesFont;
		//-----------------------------------------------------------------//
		//Default font object for DataLabels
		//-----------------------------------------------------------------//
		var dataLabelsFont = new StyleObject ();
		dataLabelsFont.name = "_SdDataLabelsFont";
		dataLabelsFont.align = "center";
		dataLabelsFont.valign = "bottom";
		dataLabelsFont.font = this.params.catFont;
		dataLabelsFont.size = this.params.catFontSize;
		dataLabelsFont.color = this.params.catFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.DATALABELS, dataLabelsFont, this.styleM.TYPE.FONT, null);
		delete dataLabelsFont;
		//-----------------------------------------------------------------//
		//Default font object for Legend
		//-----------------------------------------------------------------//
		var legendFont = new StyleObject ();
		legendFont.name = "_SdLegendFont";
		legendFont.font = this.params.outCnvBaseFont;
		legendFont.size = this.params.outCnvBaseFontSize;
		legendFont.color = this.params.outCnvBaseFontColor;
		legendFont.ishtml = 1;
		legendFont.leftmargin = 3;
		//Over-ride
		this.styleM.overrideStyle (this.objects.LEGEND, legendFont, this.styleM.TYPE.FONT, null);
		delete legendFont;
		//-----------------------------------------------------------------//
		//Default font object for DataValues
		//-----------------------------------------------------------------//
		var dataValuesFont = new StyleObject ();
		dataValuesFont.name = "_SdDataValuesFont";
		dataValuesFont.align = "center";
		dataValuesFont.valign = "middle";
		dataValuesFont.font = this.params.baseFont;
		dataValuesFont.size = this.params.baseFontSize;
		dataValuesFont.color = this.params.baseFontColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.DATAVALUES, dataValuesFont, this.styleM.TYPE.FONT, null);
		delete dataValuesFont;
		//-----------------------------------------------------------------//
		//Default font object for ToolTip
		//-----------------------------------------------------------------//
		var toolTipFont = new StyleObject ();
		toolTipFont.name = "_SdToolTipFont";
		toolTipFont.font = this.params.baseFont;
		toolTipFont.size = this.params.baseFontSize;
		toolTipFont.color = this.params.baseFontColor;
		toolTipFont.bgcolor = this.params.toolTipBgColor;
		toolTipFont.bordercolor = this.params.toolTipBorderColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.TOOLTIP, toolTipFont, this.styleM.TYPE.FONT, null);
		delete toolTipFont;
		//-----------------------------------------------------------------//
		//Default font object for V-line labels
		//-----------------------------------------------------------------//
		var vLineLabelsFont = new StyleObject ();
		vLineLabelsFont.name = "_SdDataVLineLabelsFont";
		vLineLabelsFont.align = "center";
		vLineLabelsFont.valign = "bottom";
		vLineLabelsFont.font = this.params.baseFont;
		vLineLabelsFont.size = this.params.baseFontSize;
		vLineLabelsFont.color = this.params.baseFontColor;
		vLineLabelsFont.bgcolor = this.params.canvasBgColor;
		//Over-ride
		this.styleM.overrideStyle (this.objects.VLINELABELS, vLineLabelsFont, this.styleM.TYPE.FONT, null);
		delete vLineLabelsFont;
		//-----------------------------------------------------------------//
		//Default Effect (Shadow) object for DataPlot
		//-----------------------------------------------------------------//
		if (this.params.showShadow)
		{
			var dataPlotShadow = new StyleObject ();
			dataPlotShadow.name = "_SdDataPlotShadow";
			dataPlotShadow.distance = 3;
			dataPlotShadow.angle = 315;
			dataPlotShadow.alpha = 75;
			dataPlotShadow.color = "666666";
			//Over-ride
			this.styleM.overrideStyle (this.objects.DATAPLOT, dataPlotShadow, this.styleM.TYPE.SHADOW, null);
			delete dataPlotShadow;
		}
		//-----------------------------------------------------------------//
		//Default Effect (Shadow) object for Legend
		//-----------------------------------------------------------------//
		if (this.params.legendShadow)
		{
			var legendShadow = new StyleObject ();
			legendShadow.name = "_SdLegendShadow";
			legendShadow.distance = 2;
			legendShadow.alpha = 90;
			legendShadow.angle = 45;
			//Over-ride
			this.styleM.overrideStyle (this.objects.LEGEND, legendShadow, this.styleM.TYPE.SHADOW, null);
			delete legendShadow;
		}
		//-----------------------------------------------------------------//
		//Default Animation object for DataPlot (if required)
		//-----------------------------------------------------------------//
		if (this.params.defaultAnimation)
		{
			var dataPlotAnim = new StyleObject ();
			dataPlotAnim.name = "_SdDataPlotAnim";
			dataPlotAnim.param = "_xscale";
			dataPlotAnim.easing = "regular";
			dataPlotAnim.wait = 0;
			dataPlotAnim.start = 0;
			dataPlotAnim.duration = 1;
			//Over-ride
			this.styleM.overrideStyle (this.objects.DATAPLOT, dataPlotAnim, this.styleM.TYPE.ANIMATION, "_xscale");
			delete dataPlotAnim;
		}
		//-----------------------------------------------------------------//
	}
	/**
	* calcVLinesPos method calculates the y position for the various
	* vLines defined. Also, it validates them.
	*/
	private function calcVLinesPos ()
	{
		var i : Number;
		//Iterate through all the vLines
		for (i = 1; i <= numVLines; i ++)
		{
			//If the vLine is after 1st data and before last data
			if (this.vLines [i].index > 0 && this.vLines [i].index < this.num)
			{
				//Set it's y position
				this.vLines [i].y = this.categories [this.vLines [i].index].y + (this.categories [this.vLines [i].index + 1].y - this.categories [this.vLines [i].index].y) * this.vLines[i].linePosition;
			} else 
			{
				//Invalidate it
				this.vLines [i].isValid = false;
			}
		}
	}
	/**
	* calculatePoints method calculates the various points on the chart.
	*/
	private function calculatePoints ()
	{
		//Loop variable
		var i : Number;
		var j : Number;
		//Feed empty data - By default there should be equal number of <categories>
		//and <set> element within each dataset. If in case, <set> elements fall short,
		//we need to append empty data at the end.
		for (i = 1; i <= this.numDS; i ++)
		{
			for (j = 1; j <= this.num; j ++)
			{
				if (this.dataset [i].data [j] == undefined)
				{
					this.dataset [i].data [j] = this.returnDataAsObject (NaN);
				}
			}
		}
		//Format all the numbers on the chart and store their display values
		//We format and store here itself, so that later, whenever needed,
		//we just access displayValue instead of formatting once again.
		//Also set tool tip text values
		var toolText : String
		for (i = 1; i <= this.numDS; i ++)
		{
			for (j = 1; j <= this.num; j ++)
			{
				//Format and store
				this.dataset [i].data [j].displayValue = formatNumber (this.dataset [i].data [j].value, this.params.formatNumber, this.params.decimals, this.params.forceDecimals, this.params.formatNumberScale, this.params.defaultNumberScale, this.config.nsv, this.config.nsu, this.params.numberPrefix, this.params.numberSuffix);
				//Store formatted values
				this.dataset [i].data [j].formattedValue = this.dataset [i].data [j].displayValue;
				//Format sum of values
				if (this.params.showSum && (i == 1))
				{
					this.sums [j].displayValue = formatNumber (this.sums [j].sum, this.params.formatNumber, this.params.decimals, this.params.forceDecimals, this.params.formatNumberScale, this.params.defaultNumberScale, this.config.nsv, this.config.nsu, this.params.numberPrefix, this.params.numberSuffix);
				}
				//Tool tip text.
				//Preferential Order - Set Tool Text (No concatenation) > SeriesName + Cat Name + Value
				if (this.dataset [i].data [j].toolText == undefined || this.dataset [i].data [j].toolText == "")
				{
					//If the tool tip text is not already defined
					//If labels have been defined
					toolText = (this.params.seriesNameInToolTip && this.dataset [i].seriesName != "") ? (this.dataset [i].seriesName + this.params.toolTipSepChar) : "";
					toolText = toolText + ((this.categories [j].toolText != "") ? (this.categories [j].toolText + this.params.toolTipSepChar) : "");
					toolText = toolText + this.dataset [i].data [j].displayValue;
					this.dataset [i].data [j].toolText = toolText;
				}
				if (this.dataset[i].data[j].exDispVal != "") {
					this.dataset[i].data[j].displayValue = this.dataset[i].data[j].exDispVal;
				}
			}
		}
		//Based on label step, set showLabel of each data point as required.
		//Visible label count
		var visibleCount : Number = 0;
		var finalVisibleCount : Number = 0;
		for (i = 1; i <= this.num; i ++)
		{
			//Now, the label can be preset to be hidden (set via XML)
			if (this.categories [i].showLabel)
			{
				visibleCount ++;
				//If label step is defined, we need to set showLabel of those
				//labels which fall on step as false.
				if ((i - 1) % this.params.labelStep == 0)
				{
					this.categories [i].showLabel = true;
				} else
				{
					this.categories [i].showLabel = false;
				}
			}
			//Update counter
			finalVisibleCount = (this.categories [i].showLabel) ? (finalVisibleCount + 1) : (finalVisibleCount);
		}
		
		//-----------------------------------------------------------------------------------//
		//Now, we need to calculate the available Height on the canvas.
		//Available height = total Chart height minus the list below
		// - Chart Top and Bottom Margins
		// - Space for Caption, Sub Caption and caption padding
		// - yAxisName (if to be shown)
		// - yAxisValues
		// - Trend line values
		//Initialize canvasHeight to total height minus margins
		var canvasHeight : Number = this.height - (this.params.chartTopMargin + this.params.chartBottomMargin);
		//Set canvasStartY
		var canvasStartY : Number = this.params.chartTopMargin;
		//Now, if we've to show caption
		if (this.params.caption != "")
		{
			//Create text field to get height
			var captionObj : Object = createText (true, this.params.caption, this.tfTestMC, 1, testTFX, testTFY, 0, this.styleM.getTextStyle (this.objects.CAPTION) , true, this.width, this.height/4);
			//Store the height
			canvasStartY = canvasStartY + captionObj.height;
			canvasHeight = canvasHeight - captionObj.height;
			//Create element for caption - to store width & height
			this.elements.caption = returnDataAsElement (0, 0, captionObj.width, captionObj.height);
			delete captionObj;
		}
		//Now, if we've to show sub-caption
		if (this.params.subCaption != "")
		{
			//Create text field to get height
			var subCaptionObj : Object = createText (true, this.params.subCaption, this.tfTestMC, 1, testTFX, testTFY, 0, this.styleM.getTextStyle (this.objects.SUBCAPTION) , true, this.width, this.height/4);
			//Store the height
			canvasStartY = canvasStartY + subCaptionObj.height;
			canvasHeight = canvasHeight - subCaptionObj.height;
			//Create element for sub caption - to store height
			this.elements.subCaption = returnDataAsElement (0, 0, subCaptionObj.width, subCaptionObj.height);
			delete subCaptionObj;
		}
		//Now, if either caption or sub-caption was shown, we also need to adjust caption padding
		if (this.params.caption != "" || this.params.subCaption != "")
		{
			//Account for padding
			canvasStartY = canvasStartY + this.params.captionPadding;
			canvasHeight = canvasHeight - this.params.captionPadding;
		}		
		//Accomodate space for yAxisName (if to be shown);
		if (this.params.yAxisName != "")
		{
			//Create text field to get height
			var yAxisNameObj : Object = createText (true, this.params.yAxisName, this.tfTestMC, 1, testTFX, testTFY, 0, this.styleM.getTextStyle (this.objects.YAXISNAME) , false, 0, 0);
			//Store the height
			canvasHeight = canvasHeight - yAxisNameObj.height - this.params.yAxisNamePadding;
			//Object to store width and height of yAxisName
			this.elements.yAxisName = returnDataAsElement (0, 0, yAxisNameObj.width, yAxisNameObj.height);
			delete yAxisNameObj;
		}
		
		//Accomodate height for y-axis values. Now, y-axis values conists of two parts
		//(for backward compatibility) - limits (upper and lower) and div line values.
		//So, we'll have to individually run through both of them.
		var yAxisValMaxHeight : Number = 0;
		this.config.yValAreaHeight = 0;
		var divLineObj : Object;
		var divStyle : Object = this.styleM.getTextStyle (this.objects.YAXISVALUES);
		//Iterate through all the div line values
		for (i = 1; i < this.divLines.length; i ++)
		{
			//If div line value is to be shown
			if (this.divLines [i].showValue)
			{
				//If it's the first or last div Line (limits), and it's to be shown
				if ((i == 1) || (i == this.divLines.length - 1))
				{
					if (this.params.showLimits)
					{
						//Get the width of the text
						divLineObj = createText (true, this.divLines [i].displayValue, this.tfTestMC, 1, testTFX, testTFY, 0, divStyle, false, 0, 0);
						//Accomodate
						yAxisValMaxHeight = (divLineObj.height > yAxisValMaxHeight) ? (divLineObj.height) : (yAxisValMaxHeight);
					}
				} else 
				{
					//It's a div interval - div line
					//So, check if we've to show div line values
					if (this.params.showDivLineValues)
					{
						//Get the width of the text
						divLineObj = createText (true, this.divLines [i].displayValue, this.tfTestMC, 1, testTFX, testTFY, 0, divStyle, false, 0, 0);
						//Accomodate
						yAxisValMaxHeight = (divLineObj.height > yAxisValMaxHeight) ? (divLineObj.height) : (yAxisValMaxHeight);
					}
				}
			}
		}
		//Accomodate
		if (yAxisValMaxHeight>0){
			canvasHeight = canvasHeight - yAxisValMaxHeight - this.params.yAxisValuesPadding;
			//Store y-values height - will be used when we render trend-values later.
			this.config.yValAreaHeight = yAxisValMaxHeight + this.params.yAxisValuesPadding;
		}		
		delete divLineObj;
		//Also iterate through all trend lines values
		var trendValHeight:Number = 0;
		this.config.trendValAreaHeight = 0;
		//Get style object		
		var trendStyle : Object = this.styleM.getTextStyle (this.objects.TRENDVALUES);
		var trendObj : Object;
		for (i = 1; i <= this.numTrendLines; i ++)
		{
			if (this.trendLines [i].isValid == true)
			{
				//If it's a valid trend line and value is to be shown on left
				//Get the width of the text
				trendObj = createText (true, this.trendLines [i].displayValue, this.tfTestMC, 1, testTFX, testTFY, 0, trendStyle, false, 0, 0);
				//Accomodate
				trendValHeight = (trendObj.height > trendValHeight) ? (trendObj.height) : (trendValHeight);
			}
		}
		//Accomodate
		if (trendValHeight>0){
			canvasHeight = canvasHeight - trendValHeight - this.params.yAxisValuesPadding;
			//Store trend-values height - will be used when we render y-axis name later.
			this.config.trendValAreaHeight = trendValHeight + this.params.yAxisValuesPadding;			
		}
		//We have canvas start Y and canvas height now	
		
		//We now need to calculate the available Width on the canvas.
		//Available width = total Chart width minus the list below
		// - Left and Right Margin
		// - xAxisName (if to be shown)
		// - Data labels
		var canvasWidth : Number = this.width - (this.params.chartLeftMargin + this.params.chartRightMargin);
		//Set canvas startX
		var canvasStartX : Number = this.params.chartLeftMargin;
		//Now, if x-axis name is to be shown, simulate it and get the width
		if (this.params.xAxisName != "")
		{
			//Get style object
			var xAxisNameStyle : Object = this.styleM.getTextStyle (this.objects.XAXISNAME);
			if (this.params.rotateXAxisName)
			{
				//Create text field to get width
				var xAxisNameObj : Object = createText (true, this.params.xAxisName, this.tfTestMC, 1, testTFX, testTFY, 90, xAxisNameStyle, false, 0, 0);
				//Accomodate width and padding
				canvasStartX = canvasStartX + xAxisNameObj.width + this.params.xAxisNamePadding;
				canvasWidth = canvasWidth - xAxisNameObj.width - this.params.xAxisNamePadding;
				//Create element for xAxisName - to store width/height
				this.elements.xAxisName = returnDataAsElement (0, 0, xAxisNameObj.width, xAxisNameObj.height);
			}else
			{
				//If the x-axis name is not to be rotated
				//Calculate the width of the text if in full horizontal mode
				//Create text field to get width
				var xAxisNameObj : Object = createText (true, this.params.xAxisName, this.tfTestMC, 1, testTFX, testTFY, 0, xAxisNameStyle, false, 0, 0);
				//Get a value for this.params.xAxisNameWidth
				this.params.xAxisNameWidth = Number (getFV (this.params.xAxisNameWidth, xAxisNameObj.width));
				//Get the lesser of the width (to avoid un-necessary space)
				this.params.xAxisNameWidth = Math.min (this.params.xAxisNameWidth, xAxisNameObj.width);
				//Accomodate width and padding
				canvasStartX = canvasStartX + this.params.xAxisNameWidth + this.params.xAxisNamePadding;
				canvasWidth = canvasWidth - this.params.xAxisNameWidth - this.params.xAxisNamePadding;
				//Create element for xAxisName - to store width/height
				this.elements.xAxisName = returnDataAsElement (0, 0, this.params.xAxisNameWidth, xAxisNameObj.height);
			}
			delete xAxisNameStyle;
			delete xAxisNameObj;
		}
		
		//Now, if data labels are to be shown, we need to account for their widths
		//Placeholder to store max width
		this.config.maxLabelWidth = 0;
		var labelObj : Object;
		var labelStyleObj : Object = this.styleM.getTextStyle (this.objects.DATALABELS);
		//We iterate through all the labels to get max width
		for (i = 1; i <= this.num; i ++)
		{
			//If the label is to be shown
			if (this.categories [i].showLabel)
			{
				//Create text box and get height
				labelObj = createText (true, this.categories[i].label, this.tfTestMC, 1, testTFX, testTFY, 0, labelStyleObj, false, 0, 0);
				//Store the larger
				this.config.maxLabelWidth = (labelObj.width > this.config.maxLabelWidth) ? (labelObj.width) : (this.config.maxLabelWidth);
			}
		}
		if (this.config.maxLabelWidth > 0)
		{
			//Deduct the calculated label width from canvas width
			canvasWidth = canvasWidth - this.config.maxLabelWidth - this.params.labelPadding;
			canvasStartX = canvasStartX + this.config.maxLabelWidth + this.params.labelPadding;
		}
		//Delete objects
		delete labelObj;
		delete labelStyleObj;		
		//We have canvas Width and canvas Start X now

		//We now check whether the legend is to be drawn
		if (this.params.showLegend)
		{
			//Object to store dimensions
			var lgndDim : Object;
			//Create container movie clip for legend
			this.lgndMC = this.cMC.createEmptyMovieClip ("Legend", this.dm.getDepth ("LEGEND"));
			//Create instance of legend
			if (this.params.legendPosition == "BOTTOM")
			{
				//Maximum Height - 50% of stage
				lgnd = new Legend (lgndMC, this.styleM.getTextStyle (this.objects.LEGEND) , this.params.legendPosition, canvasStartX + canvasWidth / 2, this.height / 2, canvasWidth, (this.height - (this.params.chartTopMargin + this.params.chartBottomMargin)) * 0.5, this.params.legendAllowDrag, this.width, this.height, this.params.legendBgColor, this.params.legendBgAlpha, this.params.legendBorderColor, this.params.legendBorderThickness, this.params.legendBorderAlpha, this.params.legendScrollBgColor, this.params.legendScrollBarColor, this.params.legendScrollBtnColor);
			} 
			else
			{
				//Maximum Width - 40% of stage
				lgnd = new Legend (lgndMC, this.styleM.getTextStyle (this.objects.LEGEND) , this.params.legendPosition, this.width / 2, canvasStartY + canvasHeight / 2, (this.width - (this.params.chartLeftMargin + this.params.chartRightMargin)) * 0.4, canvasHeight, this.params.legendAllowDrag, this.width, this.height, this.params.legendBgColor, this.params.legendBgAlpha, this.params.legendBorderColor, this.params.legendBorderThickness, this.params.legendBorderAlpha, this.params.legendScrollBgColor, this.params.legendScrollBarColor, this.params.legendScrollBtnColor);
			}
			//Feed data set series Name for legend
			if (this.params.reverseLegend){
				for (i = this.numDS; i >= 1; i --)
				{
					if (this.dataset [i].includeInLegend && this.dataset [i].seriesName != "")
					{
						lgnd.addItem (this.dataset [i].seriesName, this.dataset [i].color);
					}
				}
			}else{
				for (i = 1; i <= this.numDS; i ++)
				{
					if (this.dataset [i].includeInLegend && this.dataset [i].seriesName != "")
					{
						lgnd.addItem (this.dataset [i].seriesName, this.dataset [i].color);
					}
				}
			}
			//If user has defined a caption for the legend, set it
			if (this.params.legendCaption!=""){
				lgnd.setCaption(this.params.legendCaption);
			}
			//Whether to use circular marker
			lgnd.useCircleMarker(this.params.legendMarkerCircle);
			if (this.params.legendPosition == "BOTTOM")
			{
				lgndDim = lgnd.getDimensions ();
				//Now deduct the height from the calculated canvas height
				canvasHeight = canvasHeight - lgndDim.height - this.params.legendPadding;
				//Re-set the legend position
				this.lgnd.resetXY (canvasStartX + canvasWidth / 2, this.height - this.params.chartBottomMargin - lgndDim.height / 2);
			} 
			else
			{
				//Get dimensions
				lgndDim = lgnd.getDimensions ();
				//Now deduct the width from the calculated canvas width
				canvasWidth = canvasWidth - lgndDim.width - this.params.legendPadding;
				//Right position
				this.lgnd.resetXY (this.width - this.params.chartRightMargin - lgndDim.width / 2, canvasStartY + canvasHeight / 2);
			}
		}
		//----------- HANDLING CUSTOM CANVAS MARGINS --------------//
		//Before doing so, we take into consideration, user's forced canvas margins (if any defined)
		//If the user's forced values result in overlapping of chart items, we ignore.
		if (this.params.canvasLeftMargin!=-1 && this.params.canvasLeftMargin>canvasStartX){
			//Update width (deduct the difference)
			canvasWidth = canvasWidth - (this.params.canvasLeftMargin-canvasStartX);
			//Update left start position
			canvasStartX = this.params.canvasLeftMargin;		
		}
		if (this.params.canvasRightMargin!=-1 && (this.params.canvasRightMargin>(this.width - (canvasStartX+canvasWidth)))){
			//Update width (deduct the difference)
			canvasWidth = canvasWidth - (this.params.canvasRightMargin-(this.width - (canvasStartX+canvasWidth)));			
		}
		if (this.params.canvasTopMargin!=-1 && this.params.canvasTopMargin>canvasStartY){
			//Update height (deduct the difference)
			canvasHeight = canvasHeight - (this.params.canvasTopMargin-canvasStartY);
			//Update top start position
			canvasStartY = this.params.canvasTopMargin;		
		}
		if (this.params.canvasBottomMargin!=-1 && (this.params.canvasBottomMargin>(this.height - (canvasStartY+canvasHeight)))){
			//Update height(deduct the difference)
			canvasHeight = canvasHeight - (this.params.canvasBottomMargin-(this.height - (canvasStartY+canvasHeight)));
		}
		//------------ END OF CUSTOM CANVAS MARGIN HANDLING --------------------//
		//Create an element to represent the canvas now.
		this.elements.canvas = returnDataAsElement (canvasStartX, canvasStartY, canvasWidth, canvasHeight);
		//Now, we have the size for the entire chart canvas
		//The canvas comprises of two things - canvas background and canvas base
		//The width and slant height of canvas base depends on the number of bars and height (depth) of each bar
		//Now, we will calculate the space to be alloted to the canvasBg and canvasBase
		//First, depending on the number of bars, calculate the height of each bar.
		var barHeight : Number = ((this.elements.canvas.h - this.params.canvasBgDepth - 2 * this.params.canvasPadding) * ((100 - this.params.plotSpacePercent) / 100)) / (this.num);
		//Set the flag for overlapBars based on bar width
		//We overlap bars only if the bar height < this.params.maxBarHeight
		var overlapBars : Number = (barHeight < this.params.maxBarHeight) ?1 : 0;
		this.params.overlapBars = toBoolean (getFN (this.params.overlapBars, overlapBars));
		//If overlap is false or num bars==1, we check against max height of bars
		if ( ! this.params.overlapBars || this.num == 1)
		{
			barHeight = (barHeight > this.params.maxBarHeight) ? this.params.maxBarHeight : barHeight;
		}
		//Calculate and store the shifts
		this.config.shifts = Bar3D.calcShifts (barHeight, 45, this.params.barDepth);
		//Now, if we've to overlap bars (with number of bars >1)
		//we need to re-calculate bar height
		if (this.params.overlapBars && this.num > 1)
		{
			//Set spacing to 0 - as bars would now overlap each other
			this.params.plotSpacePercent = 0;
			//Get the maximum possible y-space that the shadow of all bars can take.
			var totalShadow : Number = (this.config.shifts.hShadow) * (this.num);
			//Do a conditional check to alter total shadow space
			if (this.config.shifts.hShadow >= this.config.shifts.hFront)
			{
				//If the bars are high depth bars.
				totalShadow = totalShadow * (this.config.shifts.hFront / this.config.shifts.hShadow);
			} else
			{
				//Low depth bars - more height on front side.
				totalShadow = totalShadow * 0.5;
			}
			//Get new bar height based on the above calculated figures
			barHeight = ((this.elements.canvas.h - this.params.canvasBgDepth) + (totalShadow * 0.5) - (2 * this.params.canvasPadding)) / (this.num);
			//Re-calculate the bar 3D Shifts
			this.config.shifts = Bar3D.calcShifts (barHeight, 45, this.params.barDepth);
		}
		//Now, store canvas base and canvas bg as elements of chart
		this.elements.canvasBg = returnDataAsElement (this.elements.canvas.x + this.params.canvasBaseDepth + this.config.shifts.xShift, this.elements.canvas.y + this.params.canvasBgDepth, this.elements.canvas.w - this.params.canvasBaseDepth - this.config.shifts.xShift, this.elements.canvas.h - this.params.canvasBgDepth- ((this.config.zeroPRequired==true)?this.config.shifts.yShift:0));
		this.elements.canvasBase = returnDataAsElement (this.elements.canvas.x + this.params.canvasBaseDepth, this.elements.canvasBg.y + this.config.shifts.yShift, this.config.shifts.xShift, this.elements.canvasBg.h);
		
		//Reset legend position again - to keep it at center of bg
		if (this.params.legendPosition == "BOTTOM")
		{
			lgndDim = lgnd.getDimensions ();
			//Re-set the legend position
			this.lgnd.resetXY (this.elements.canvasBg.x + this.elements.canvasBg.w/2, this.height - this.params.chartBottomMargin - lgndDim.height / 2);
		}
		var barSpace:Number;
		//Calculate space between two bars
		if (this.num > 2)
		{
			//Equally distribute them on the canvas.
			var barSpace : Number = ((this.elements.canvasBg.h - 2 * this.params.canvasPadding) - (barHeight * this.num)) / (this.num - 1);
		} else
		{
			//If it's only 1 or 2 bars, we center align them instead of equal distribution.
			var barSpace : Number = ((this.elements.canvasBg.h - 2 * this.params.canvasPadding) - (barHeight * this.num)) / (this.num + 1);
		}
		//We finally have bar height and space
		//Store it in config
		this.config.barHeight = barHeight;
		this.config.barSpace = barSpace;
		//We now need to calculate the position of bars on the chart.
		//Base Plane position - Base plane is the y-plane from which bars start.
		//If there's a 0 value in between yMin,yMax, base plane represents 0 value.
		if (this.config.yMax >= 0 && this.config.yMin < 0)
		{
			//Negative number present - so set basePlanePos as 0 value
			this.config.basePlanePos = this.getAxisPosition (0, this.config.yMax, this.config.yMin, this.elements.canvasBg.x, this.elements.canvasBg.toX, false, 0);
		} else 
		{
			//No negative numbers - so set basePlanePos as yMin value
			this.config.basePlanePos = this.getAxisPosition (this.config.yMin, this.config.yMax, this.config.yMin, this.elements.canvasBg.x, this.elements.canvasBg.toX, false, 0);
		}
		//Store referential depths for each stacked bar
		for (i = 1; i <= this.num; i ++)
		{
			var pDepth : Number = this.numDS + 1;
			//Negative depth goes reverse
			var nDepth : Number = this.numDS;
			for (j = 1; j <= this.numDS; j ++)
			{
				//If the data is defined
				if (this.dataset [j].data [i].isDefined)
				{
					if (this.dataset [j].data [i].value >= 0)
					{
						this.dataset [j].data [i].depth = pDepth;
						pDepth ++;
					} else
					{
						this.dataset [j].data [i].depth = nDepth;
						nDepth --;
					}
				}
			}
		}
		var dataEndX : Number;
		//Now, store the positions of the bars
		for (i = 1; i <= this.num; i ++)
		{
			//Position co-ordinates
			var posX : Number = 0;
			var negX : Number = 0;
			//Categories y-Position
			if (this.num > 2)
			{
				this.categories [i].y = this.elements.canvasBg.y + this.params.canvasPadding + (barSpace * (i - 1)) + ((i - 0.5) * barHeight) + this.config.shifts.yShift;
			} else
			{
				this.categories [i].y = this.elements.canvasBg.y + this.params.canvasPadding + (barSpace * i) + ((i - 0.5) * barHeight) + this.config.shifts.yShift;
			}
			//Iterate through all data sets for each index
			for (j = 1; j <= this.numDS; j ++)
			{
				if (this.dataset [j].data [i].isDefined)
				{
					//Y-Position of the bar
					this.dataset [j].data [i].y = this.categories [i].y;
					//Width for each bar
					dataEndX = this.getAxisPosition (this.dataset [j].data [i].value, this.config.yMax, this.config.yMin, this.elements.canvasBg.x, this.elements.canvasBg.toX, false, 0);
					this.dataset [j].data [i].w = (dataEndX - this.config.basePlanePos);
					//Set the x position
					this.dataset [j].data [i].x = ((this.dataset [j].data [i].w >= 0) ?posX : negX) + this.config.basePlanePos - this.config.shifts.xShift;
					//Store value textbox x position
					this.dataset [j].data [i].valTBX = this.dataset [j].data [i].x + (this.dataset [j].data [i].w / 2);
					//Update x-co ordinates
					if (this.dataset [j].data [i].w >= 0)
					{
						posX = posX + this.dataset [j].data [i].w;
					} else
					{
						negX = negX + this.dataset [j].data [i].w;
					}
					//Height
					this.dataset [j].data [i].h = barHeight;
				}
			}
			//Store positive end X and negative end X in sums
			this.sums [i].pX = posX;
			this.sums [i].nX = negX;
		}
	}
	/**
	* allotDepths method allots the depths for various chart objects
	* to be rendered. We do this before hand, so that we can later just
	* go on rendering chart objects, without swapping.
	*/
	private function allotDepths () : Void
	{
		//Background
		this.dm.reserveDepths ("BACKGROUND", 1);
		//Click URL Handler
		this.dm.reserveDepths ("CLICKURLHANDLER", 1);
		//Background SWF
		this.dm.reserveDepths ("BGSWF", 1);
		//Canvas
		this.dm.reserveDepths ("CANVASBG", 1);
		this.dm.reserveDepths ("CANVASBASE", 1);
		//Div Lines and their labels
		this.dm.reserveDepths ("DIVLINES", (this.divLines.length * 2));
		//Caption
		this.dm.reserveDepths ("CAPTION", 1);
		//Sub-caption
		this.dm.reserveDepths ("SUBCAPTION", 1);
		//X-Axis Name
		this.dm.reserveDepths ("XAXISNAME", 1);
		//Y-Axis Name
		this.dm.reserveDepths ("YAXISNAME", 1);
		//Trend lines plot (lines and their labels)
		this.dm.reserveDepths ("TRENDLINES", this.numTrendLines);
		this.dm.reserveDepths ("TRENDVALUES", this.numTrendLines);
		//Vertical div lines
		this.dm.reserveDepths ("VLINES", this.numVLines);
		//Vertical div lines labels
		this.dm.reserveDepths ("VLINELABELS", this.numVLines);
		//Data Labels
		this.dm.reserveDepths ("DATALABELS", this.num);
		//Data Bars - Negative values
		this.dm.reserveDepths ("DATAPLOTNEG", this.num);
		//Zero Plane
		this.dm.reserveDepths ("ZEROPLANE", 2);
		//Data Bars - Positive Values
		this.dm.reserveDepths ("DATAPLOTPOS", this.num);
		//Data Values
		this.dm.reserveDepths ("DATAVALUES", this.num * this.numDS);
		//Data Sums
		this.dm.reserveDepths ("DATASUM", this.num);
		//Legend
		this.dm.reserveDepths ("LEGEND", 1);
	}
	//--------------- VISUAL RENDERING METHODS -------------------------//
	/**
	* drawHeaders method renders the following on the chart:
	* CAPTION, SUBCAPTION, XAXISNAME, YAXISNAME
	*/
	private function drawHeaders ()
	{
		//Render caption
		if (this.params.caption != "")
		{
			var captionStyleObj : Object = this.styleM.getTextStyle (this.objects.CAPTION);
			captionStyleObj.align = "center";
			captionStyleObj.vAlign = "bottom";
			var captionObj : Object = createText (false, this.params.caption, this.cMC, this.dm.getDepth ("CAPTION") , this.x + (this.width / 2) , this.params.chartTopMargin, 0, captionStyleObj, true, this.elements.caption.w, this.elements.caption.h);
			//Apply animation
			if (this.params.animation)
			{
				this.styleM.applyAnimation (captionObj.tf, this.objects.CAPTION, this.macro, this.x + (this.width / 2) - (this.elements.caption.w / 2) , 0, this.params.chartTopMargin, 0, 100, null, null, null);
			}
			//Apply filters
			this.styleM.applyFilters (captionObj.tf, this.objects.CAPTION);
			//Delete
			delete captionObj;
			delete captionStyleObj;
		}
		//Render sub caption
		if (this.params.subCaption != "")
		{
			var subCaptionStyleObj : Object = this.styleM.getTextStyle (this.objects.SUBCAPTION);
			subCaptionStyleObj.align = "center";
			subCaptionStyleObj.vAlign = "top";
			var subCaptionObj : Object = createText (false, this.params.subCaption, this.cMC, this.dm.getDepth ("SUBCAPTION") , this.x + (this.width / 2) , this.elements.canvasBg.y - this.params.captionPadding, 0, subCaptionStyleObj, true, this.elements.subCaption.w, this.elements.subCaption.h);
			//Apply animation
			if (this.params.animation)
			{
				this.styleM.applyAnimation (subCaptionObj.tf, this.objects.SUBCAPTION, this.macro, this.x + (this.width / 2) - (this.elements.subCaption.w / 2) , 0, this.elements.canvasBg.y - this.params.captionPadding - this.elements.subCaption.h, 0, 100, null, null, null);
			}
			//Apply filters
			this.styleM.applyFilters (subCaptionObj.tf, this.objects.SUBCAPTION);
			//Delete
			delete subCaptionObj;
			delete subCaptionStyleObj;
		}
		//Render y-axis name
		if (this.params.yAxisName != "")
		{
			var yAxisNameStyleObj : Object = this.styleM.getTextStyle (this.objects.YAXISNAME);
			yAxisNameStyleObj.align = "center";
			yAxisNameStyleObj.vAlign = "bottom";
			var yAxisNameObj : Object = createText (false, this.params.yAxisName, this.cMC, this.dm.getDepth ("YAXISNAME") , this.elements.canvasBg.x + (this.elements.canvasBg.w / 2) , this.elements.canvas.toY + this.config.yValAreaHeight + this.config.trendValAreaHeight + this.params.yAxisNamePadding, 0, yAxisNameStyleObj, false, 0, 0);
			//Apply animation
			if (this.params.animation)
			{
				this.styleM.applyAnimation (yAxisNameObj.tf, this.objects.YAXISNAME, this.macro, yAxisNameObj.tf._x , 0, yAxisNameObj.tf._y, 0, 100, null, null, null);
			}
			//Apply filters
			this.styleM.applyFilters (yAxisNameObj.tf, this.objects.YAXISNAME);
			//Delete
			delete yAxisNameObj;
			delete yAxisNameStyleObj;
		}
		//Render x-axis name
		if (this.params.xAxisName != "")
		{
			var xAxisNameStyleObj : Object = this.styleM.getTextStyle (this.objects.XAXISNAME);
			//Set alignment parameters
			xAxisNameStyleObj.align = "left";
			xAxisNameStyleObj.vAlign = "middle";
			//If the name is to be rotated
			if (this.params.rotateXAxisName)
			{
				var xAxisNameObj : Object = createText (false, this.params.xAxisName, this.cMC, this.dm.getDepth ("XAXISNAME") , this.params.chartLeftMargin, this.elements.canvasBase.y + (this.elements.canvasBase.h / 2) , 270, xAxisNameStyleObj, false, 0, 0);
				//Apply animation
				if (this.params.animation)
				{
					this.styleM.applyAnimation (xAxisNameObj.tf, this.objects.XAXISNAME, this.macro, xAxisNameObj.tf._x, 0, xAxisNameObj.tf._y , 0, 100, null, null, null);
				}
			}else
			{
				//We show horizontal name
				//Adding 1 to this.params.xAxisNameWidth and then passing to avoid line breaks
				var xAxisNameObj : Object = createText (false, this.params.xAxisName, this.cMC, this.dm.getDepth ("XAXISNAME") , this.params.chartLeftMargin, this.elements.canvasBase.y + (this.elements.canvasBase.h / 2) , 0, xAxisNameStyleObj, true, this.params.xAxisNameWidth + 1, this.elements.canvasBase.h);
				//Apply animation
				if (this.params.animation)
				{
					this.styleM.applyAnimation (xAxisNameObj.tf, this.objects.XAXISNAME, this.macro, xAxisNameObj.tf._x, 0, xAxisNameObj.tf._y, 0, 100, null, null, null);
				}
			}
			//Apply filters
			this.styleM.applyFilters (xAxisNameObj.tf, this.objects.XAXISNAME);
			//Delete
			delete xAxisNameObj;
			delete xAxisNameStyleObj;
		}
		//Clear Interval
		clearInterval (this.config.intervals.headers);
	}
	/**
	* drawLabels method draws the x-axis labels based on the oarameters.
	*/
	private function drawLabels ()
	{
		var labelObj : Object;
		var labelStyleObj : Object = this.styleM.getTextStyle (this.objects.DATALABELS);
		var depth : Number = this.dm.getDepth ("DATALABELS");
		var i : Number;
		for (i = 1; i <= this.num; i ++)
		{
			//If the label is to be shown
			if (this.categories [i].showLabel)
			{
				//Render normal label
				labelStyleObj.align = "right";
				labelStyleObj.vAlign = "middle";
				labelObj = createText (false, this.categories [i].label, this.cMC, depth, this.elements.canvasBase.x - this.params.canvasBaseDepth - this.params.labelPadding, this.categories [i].y, 0, labelStyleObj, false, 0, 0);
				//Apply filter
				this.styleM.applyFilters (labelObj.tf, this.objects.DATALABELS);
				//Apply animation
				if (this.params.animation)
				{
					this.styleM.applyAnimation (labelObj.tf, this.objects.DATALABELS, this.macro, labelObj.tf._x, 0, labelObj.tf._y, 0, 100, null, null, null);
				}
				//Increase depth
				depth ++;
			}
		}
		//Clear interval
		clearInterval (this.config.intervals.labels);
	}
	/**
	* drawBars method draws the bars on the chart
	*/
	private function drawBars ()
	{
		//Variables
		var barMC : MovieClip, pStackMC : MovieClip, nStackMC : MovieClip;
		var barIns : Bar3D;
		var posDepth : Number = this.dm.getDepth ("DATAPLOTPOS");
		var negDepth : Number = this.dm.getDepth ("DATAPLOTNEG");
		var depth : Number;
		var i : Number;
		var j : Number;
		var animX : Number;
		//Create function storage containers for Delegate functions
		var fnRollOver : Function, fnClick : Function;
		//Rendered Bar Count
		var renderedBarCount : Number = 0;
		//Iterate through all bars
		//Using reverse loop for automatic depth iteration
		for (i = this.num; i >= 1; i --)
		{
			//For each data index, we now create two movie clips:
			//PosStack_i, NegStack_i (both on conditional basis)
			//Create the positive stack movie clip (if required).
			if (this.sums [i].pSum != undefined)
			{
				pStackMC = this.cMC.createEmptyMovieClip ("PosStack_" + i, posDepth);
				posDepth ++;
			}
			if (this.sums [i].nSum != undefined)
			{
				nStackMC = this.cMC.createEmptyMovieClip ("NegStack_" + i, negDepth);
				negDepth ++;
			}
			//Shift both the movie clips down so that bars can be positioned
			//inside at 0 x - for proper xScale animation
			pStackMC._x = this.config.basePlanePos - this.config.shifts.xShift;
			nStackMC._x = this.config.basePlanePos - this.config.shifts.xShift;
			//Reset bar count
			renderedBarCount = 0;
			//Now, iterate through each bar to create the stacked bar.
			for (j = 1; j <= this.numDS; j ++)
			{
				//If the bar is defined
				if (this.dataset [j].data [i].isDefined)
				{
					//Increase count
					renderedBarCount ++;
					depth = this.dataset [j].data [i].depth;
					//Based on whether the bar is positive or negative,
					//create an empty movie clip for this bar
					if (this.dataset [j].data [i].value >= 0)
					{
						barMC = pStackMC.createEmptyMovieClip ("Bar_" + i + "_" + j, depth);
					} else
					{
						barMC = nStackMC.createEmptyMovieClip ("Bar_" + i + "_" + j, depth);
					}
					//Create bar instance
					//We're adjusting X position of the bar inside stacked movie clip
					//so that the first bar (both positive and negative) originate at 0 X
					//and the rest on referential X. We do not alter Y.
					barIns = new Bar3D (barMC, this.dataset [j].data [i].x - this.config.basePlanePos + this.config.shifts.xShift, this.dataset [j].data [i].y, this.dataset [j].data [i].w, this.config.shifts.hFront, this.config.shifts.xShift, this.config.shifts.yShift, this.dataset [j].data [i].color, this.params.showPlotBorder, this.params.plotBorderColor, this.params.plotBorderAlpha);
					//Draw the bar
					barIns.draw (this.params.use3DLighting);
					//Set the alpha of entire bar
					barMC._alpha = this.dataset [j].data [i].alpha;
					//Event handlers for tool tip
					if (this.params.showToolTip)
					{
						//Create Delegate for roll over function barOnRollOver
						fnRollOver = Delegate.create (this, barOnRollOver);
						//Set the index
						fnRollOver.dsindex = j;
						fnRollOver.index = i;
						//Assing the delegates to movie clip handler
						barMC.onRollOver = fnRollOver;
						//Set roll out and mouse move too.
						barMC.onRollOut = barMC.onReleaseOutside = Delegate.create (this, barOnRollOut);
						barMC.onMouseMove = Delegate.create (this, barOnMouseMove);
					}
					//Click handler for links - only if link for this bar has been defined and click URL
					//has not been defined.
					if (this.dataset [j].data [i].link != "" && this.dataset [j].data [i].link != undefined && this.params.clickURL == "")
					{
						//Create delegate function
						fnClick = Delegate.create (this, barOnClick);
						//Set index
						fnClick.dsindex = j;
						fnClick.index = i;
						//Assign
						barMC.onRelease = fnClick;
					} 
					else
					{
						//Do not use hand cursor
						barMC.useHandCursor = (this.params.clickURL == "") ?false : true;
					}
				}
			}
			//Apply filters (only if bar count > 0)
			if (renderedBarCount > 0)
			{
				if (pStackMC._width>0){
					//Apply shadow on positive bar MC container, only if the container
					//contains columns
					this.styleM.applyFilters (pStackMC, this.objects.DATAPLOT);
				}
				if (nStackMC._width>0){
					this.styleM.applyFilters (nStackMC, this.objects.DATAPLOT);
				}
			}
			//Apply animation (only if bar count > 0)
			if (this.params.animation && renderedBarCount > 0)
			{
				//For Positive stack
				if (this.sums [i].pSum != undefined)
				{
					//We animate xScale only if |width| > this.config.shifts.xShift*1.5
					if (Math.abs (pStackMC._width) > (this.config.shifts.xShift * 1.5))
					{
						animX = 100;
					} 
					else
					{
						animX = null;
					}
					this.styleM.applyAnimation (pStackMC, this.objects.DATAPLOT, this.macro, this.dataset [j].data [i].x, 0, this.dataset [j].data [i].y, 0, 100, animX, 100, null);
				}
				//Negative Stack
				if (this.sums [i].nSum != undefined)
				{
					//We animate xScale only if |width| > this.config.shifts.xShift*1.5
					if (Math.abs (nStackMC._width) > (this.config.shifts.xShift * 1.5))
					{
						animX = 100;
					} 
					else
					{
						animX = null;
					}
					this.styleM.applyAnimation (nStackMC, this.objects.DATAPLOT, this.macro, this.dataset [j].data [i].x, 0, this.dataset [j].data [i].y, 0, 100, animX, 100, null);
				}
			}			
		}
		//Clear interval
		clearInterval (this.config.intervals.plot);
	}
	/**
	* drawValues method draws the values on the chart.
	*/
	private function drawValues () : Void
	{
		//Get value text style
		var valueStyleObj : Object = this.styleM.getTextStyle (this.objects.DATAVALUES);
		//Container object
		var valueObj : MovieClip;
		//Depth
		var depth : Number = this.dm.getDepth ("DATAVALUES");
		//Loop var
		var i : Number;
		var j : Number;
		var yPos : Number;
		var xPos : Number;
		var align : String, vAlign : String;
		////Iterate through all bars
		for (i = 1; i <= this.numDS; i ++)
		{
			for (j = 1; j <= this.num; j ++)
			{
				//If defined and value is to be shown
				if (this.dataset [i].data [j].isDefined && this.dataset [i].data [j].showValue)
				{
					//Position
					xPos = this.dataset [i].data [j].valTBX;
					yPos = (this.dataset [i].data [j].y);
					//Convey alignment to rendering object
					valueStyleObj.align = "center";
					valueStyleObj.vAlign = "middle";
					valueObj = createText (false, this.dataset [i].data [j].displayValue, this.cMC, depth, xPos , yPos, 0, valueStyleObj, false, 0, 0);
					//Apply filter
					this.styleM.applyFilters (valueObj.tf, this.objects.DATAVALUES);
					//Apply animation
					if (this.params.animation)
					{
						this.styleM.applyAnimation (valueObj.tf, this.objects.DATAVALUES, this.macro, valueObj.tf._x, 0, valueObj.tf._y, 0, 100, null, null, null);
					}
					//Increase depth
					depth ++;
				}
			}
		}
		//Clear interval
		clearInterval (this.config.intervals.dataValues);
	}
	/**
	* drawSum method draws the sum of values on the chart.
	*/
	private function drawSum () : Void
	{
		if (this.params.showSum)
		{
			//Get value text style
			var valueStyleObj : Object = this.styleM.getTextStyle (this.objects.DATAVALUES);
			//Container object
			var valueObj : MovieClip;
			//Depth
			var depth : Number = this.dm.getDepth ("DATASUM");
			//Loop var
			var i : Number;
			var xPos : Number, yPos : Number;
			var align : String, vAlign : String;
			////Iterate through all indexs
			for (i = 1; i <= this.num; i ++)
			{
				//If defined and value is to be shown
				if (this.sums [i].sum != 0)
				{
					//Align position
					align = (this.sums [i].sum < 0) ?"right" : "left";
					//Vertical Alignment position
					vAlign = "middle";
					//Get the y position
					xPos = this.config.basePlanePos + ((this.sums [i].sum < 0) ? (this.sums [i].nX - this.config.shifts.xShift - this.params.valuePadding) : (this.sums [i].pX + this.params.valuePadding));
					//Y-position
					yPos = (this.sums [i].sum >= 0) ? (this.categories [i].y - this.config.shifts.yShift) : (this.categories [i].y);
					//Convey alignment to rendering object
					valueStyleObj.align = align;
					valueStyleObj.vAlign = vAlign;
					valueObj = createText (false, this.sums [i].displayValue, this.cMC, depth, xPos , yPos, 0, valueStyleObj, false, 0, 0);
					//Apply filter
					this.styleM.applyFilters (valueObj.tf, this.objects.DATAVALUES);
					//Apply animation
					if (this.params.animation)
					{
						this.styleM.applyAnimation (valueObj.tf, this.objects.DATAVALUES, this.macro, valueObj.tf._x, 0, valueObj.tf._y, 0, 100, null, null, null);
					}
					//Increase depth
					depth ++;
				}
			}
		}
		//Clear interval
		clearInterval (this.config.intervals.dataSum);
	}
	/**
	* drawLegend method renders the legend
	*/
	private function drawLegend () : Void
	{
		if (this.params.showLegend)
		{
			this.lgnd.render ();
			//Apply filter
			this.styleM.applyFilters (lgndMC, this.objects.LEGEND);
			//Apply animation
			if (this.params.animation)
			{
				this.styleM.applyAnimation (lgndMC, this.objects.LEGEND, this.macro, null, 0, null, 0, 100, null, null, null);
			}
		}
		//Clear interval
		clearInterval (this.config.intervals.legend);
	}
	/**
	* setContextMenu method sets the context menu for the chart.
	* For this chart, the context items are "Print Chart".
	*/
	private function setContextMenu () : Void
	{
		var chartMenu : ContextMenu = new ContextMenu ();
		chartMenu.hideBuiltInItems ();
		if (this.params.showPrintMenuItem){
			//Create a print chart contenxt menu item
			var printCMI : ContextMenuItem = new ContextMenuItem ("Print Chart", Delegate.create (this, printChart));
			//Push print item.
			chartMenu.customItems.push (printCMI);
		}
		//If the export data item is to be shown
		if (this.params.showExportDataMenuItem){
			chartMenu.customItems.push(super.returnExportDataMenuItem());
		}
		//Add export chart related menu items to the context menu
		this.addExportItemsToMenu(chartMenu);
		if (this.params.showFCMenuItem){
			//Push "About FusionCharts" Menu Item
			chartMenu.customItems.push(super.returnAbtMenuItem());		
		}
		//Assign the menu to cMC movie clip
		this.cMC.menu = chartMenu;
	}
	// -------------------- EVENT HANDLERS --------------------//
	/**
	* barOnRollOver is the delegat-ed event handler method that'll
	* be invoked when the user rolls his mouse over a bar.
	* This function is invoked, only if the tool tip is to be shown.
	* Here, we show the tool tip.
	*/
	private function barOnRollOver () : Void
	{
		//Index of bar is stored in arguments.caller.index
		var dsindex : Number = arguments.caller.dsindex;
		var index : Number = arguments.caller.index;
		//Set tool tip text
		this.tTip.setText (this.dataset [dsindex].data [index].toolText);
		//Show the tool tip
		this.tTip.show ();
	}
	/**
	* barOnRollOut method is invoked when the mouse rolls out
	* of bar. We just hide the tool tip here.
	*/
	private function barOnRollOut () : Void
	{
		//Hide the tool tip
		this.tTip.hide ();
	}
	/*
	* barOnMouseMove is called when the mouse position has changed
	* over bar. We reposition the tool tip.
	*/
	private function barOnMouseMove () : Void
	{
		//Reposition the tool tip only if it's in visible state
		if (this.tTip.visible ())
		{
			this.tTip.rePosition ();
		}
	}
	/**
	* barOnClick is invoked when the user clicks on a bar (if link
	* has been defined). We invoke the required link.
	*/
	private function barOnClick () : Void
	{
		//Index of bar is stored in arguments.caller.index
		var dsindex : Number = arguments.caller.dsindex;
		var index : Number = arguments.caller.index;
		//Invoke the link
		super.invokeLink (this.dataset [dsindex].data [index].link);
	}
	/**
	* reInit method re-initializes the chart. This method is basically called
	* when the user changes chart data through JavaScript. In that case, we need
	* to re-initialize the chart, set new XML data and again render.
	*/
	public function reInit () : Void
	{
		//Invoke super class's reInit
		super.reInit ();
		//Now initialize things that are pertinent to this class
		//but not defined in super class.
		this.categories = new Array ();
		this.dataset = new Array ();
		//Initialize the number of data elements present
		this.numDS = 0;
		this.num = 0;
		this.lgnd.reset ();
		this.negativePresent = false;
		this.positivePresent = false;
		//Array to store sum of data sets
		this.sums = new Array ();
		this.sumStored = false;
	}
	/**
	* remove method removes the chart by clearing the chart movie clip
	* and removing any listeners.
	*/
	public function remove () : Void
	{
		super.remove ();
		//Remove class pertinent objects
		this.lgnd.destroy ();
		lgndMC.removeMovieClip ();
	}
	//---------------DATA EXPORT HANDLERS-------------------//
	/**
	 * Returns the data of the chart in CSV/TSV format. The separator, qualifier and line
	 * break character is stored in params (during common parsing).
	 * @return	The data of the chart in CSV/TSV format, as specified in the XML.
	 */
	public function exportChartDataCSV():String {
		var strData:String = "";
		var strQ:String = this.params.exportDataQualifier;
		var strS:String = this.params.exportDataSeparator;
		var strLB:String = this.params.exportDataLineBreak;
		var i:Number, j:Number;
		strData = strQ + ((this.params.xAxisName!="")?(this.params.xAxisName):("Label")) + strQ + strS;
		//Add all the series names
		for (i = 1; i <= this.numDS; i++) {
			strData += strQ + ((this.dataset[i].seriesName != "")?(this.dataset[i].seriesName):("")) + strQ + ((i < this.numDS)?(strS):(strLB));
		}
		//Iterate through each data-items and add it to the output
		for (i = 1; i <= this.num; i ++)
		{
			//Add the category label
			strData += strQ + (this.categories [i].label)  + strQ + strS;
			//Add the individual value for datasets
			for (j = 1; j <= this.numDS; j ++)
			{
				 strData += strQ + ((this.dataset[j].data[i].isDefined==true)?((this.params.exportDataFormattedVal==true)?(this.dataset[j].data[i].formattedValue):(this.dataset[j].data[i].value)):(""))  + strQ + ((j<this.numDS)?strS:"");
			}
			if (i < this.num) {
				strData += strLB;
			}
		}
		return strData;
	}
}
